accounts/urls.py
"""
Connor Warner
CIS 218
2/28/24
"""

from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("restaurant_rating.urls")),
]

restaurant_rating/urls.py
"""
Connor Warner
CIS 218
2/28/24
"""

from django.urls import path
from .views import RestaurantListView, RestaurantDetailView, ReviewDetailView, ReviewCreateView, ReviewUpdateView, ReviewDeleteView

urlpatterns = [
    path("review/create/", ReviewCreateView.as_view(), name="review_create"),
    path("restaurant/<int:pk>/", RestaurantDetailView.as_view(), name="restaurant_detail"),
    path("review/<int:pk>/", ReviewDetailView.as_view(), name="review_detail"),
    path("review/<int:pk>/update/", ReviewUpdateView.as_view(), name="review_update"),
    path("review/<int:pk>/delete/", ReviewDeleteView.as_view(), name="review_delete"),
    path("", RestaurantListView.as_view(), name="home")
]

accounts/models.py
from django.db import models

# Create your models here.

restaurant_rating/models.py
"""
Connor Warner
CIS 218
2/28/24
"""

from django.db import models
from django.urls import reverse


class Restaurant(models.Model):
    """Restaurant model class"""

    name = models.CharField(max_length=150)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String method"""
        return self.name
    
    def get_absolute_url(self):
        """get the absolute URL for a single restaurant"""
        return reverse("restaurant_detail", kwargs={"pk": self.pk})



class Review(models.Model):
    """Review model class"""


    class Stars(models.IntegerChoices):
        """Star rating choices"""
        ONE_STAR = 1
        TWO_STAR = 2
        THREE_STAR = 3
        FOUR_STAR = 4
        FIVE_STAR = 5


    restaurant = models.ForeignKey(
        Restaurant,
        on_delete=models.CASCADE,
        related_name="reviews"
    )
    user = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
        related_name="reviews"
    )


    body = models.TextField()
    rating = models.IntegerField(choices=Stars.choices, default=Stars.THREE_STAR)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String method"""
        return self.body
    
    def get_absolute_url(self):
        """Get the absolute URL for a single restaurant"""
        return reverse("review_detail", kwargs={"pk": self.pk})
    

accounts/views.py
"""
Connor Warner
CIS 218
2/28/24
"""

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView



class SignUpView(CreateView):
    """Sign Up View"""

    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

restaurant_rating/views.py
"""
Connor Warner
CIS 218
2/28/24
"""

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Restaurant, Review

class RestaurantListView(ListView):
    """Restaurant List View"""
    model = Restaurant
    template_name = "home.html"


class RestaurantDetailView(DetailView):
    """Restaurant Detail View"""
    model = Restaurant
    template_name = "restaurant_detail.html"


class ReviewDetailView(DetailView):
    """Review Detail View"""
    model = Review
    template_name = "review_detail.html"


class ReviewCreateView(CreateView):
    """Review Create View"""
    model = Review
    template_name = "review_create.html"
    fields = ["restaurant", "user", "body", "rating"]

    def get_initial(self):
        """Get initial form data"""
        # Get the result of calling the parent method
        initial_data = super().get_initial()
         # Add the author so it is the requests user
        initial_data['user'] = self.request.user
        # Return the data
        return initial_data

class ReviewUpdateView(UpdateView):
    """Review Update View"""
    model = Review
    template_name = "review_update.html"
    fields = ["restaurant", "body", "rating"]


class ReviewDeleteView(DeleteView):
    """Review Delete View"""
    model = Review
    template_name = "review_delete.html"
    success_url = reverse_lazy("home")

templates/base.html
<!--
Connor Warner
CIS 218
2/28/24
-->

<html>
    <head>
        <title>Restaurant Ratings</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        
    </head>
    <body>
        <header>
              <header class="p-3 text-bg-dark">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start align-baseline">
                  <a href="{% url 'home' %}" class="d-flex align-items-center mb-2 mb-lg-0 fs-2 text-white text-decoration-none">Restaurant Reviews</a>
                    
                  <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'home' %}" class="nav-link px-2 fs-5 text-secondary ms-3">Home</a></li>
                  </ul>
                  <div class="text-end px-2">
                    {% if user.is_authenticated %}
                        {{ user.username }}
                        <a href="{% url "logout" %}" class="text-decoration-none">
                            <button type="button" class="btn btn-outline-light mx-3 ps-2">Logout</button>
                        </a>
                    {% else %}
                        <a href="{% url "login" %}" class="text-decoration-none">
                            <button type="button" class="btn btn-outline-light me-3">Login</button>
                        </a>
                        <a href="{% url "signup" %}" class="text-decoration-none">
                            <button type="button" class="btn btn-primary">Sign-up</button>
                        </a>
                    {% endif %}
                  </div>
                </div>
              </header>
        </header>
        <div class="mx-4">
            {% block content %}
            {% endblock content %}
        </div>
        <footer class="fw-light fst-italic p-2 mt-3 ms-4">
            <p>&copy 2024 - Connor Warner</p>
        </footer>
    </body>
</hmtl>

templates/home.html
<!--
Connor Warner
CIS 218
2/28/24
-->

{% extends "base.html" %}

{% block content %}
<div class="mx-4">
    <header class="py-3 mb-3 fs-1 fw-bold border-bottom">All Restaruants</header>
        {% for restaurant in restaurant_list %}
            <div class="restaurant border-bottom">
                <p class="fs-2 fw-bolder">
                    <a href="{% url "restaurant_detail" restaurant.pk %}">{{ restaurant.name }}</a>
                </p>
                <!-- TODO: Add avg stars-->
                {% if restaurant.reviews.all.count == 0 %}
                    <p>No reviews yet</p>
                {% else %}
                    <p>{{ restaurant.reviews.all.count }} Reviews</p>
                {% endif %}
            </div>
        {% endfor %}
</div>
{% endblock content %}

templates/restaurant_detail.html
<!--
Connor Warner
CIS 218
2/28/24
-->

{% extends "base.html" %}

{% block content %}
<div class="mx-4">
    <div class="border-bottom mb-4 ">
        <div class="row">
            <div class="col-9">
                <p class="fs-1 fw-bold">{{ restaurant.name }}</p>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-6">
                <p>&#128210; {{restaurant.reviews.all.count}} Reviews</p>
            </div>
            <div class="col-md-2 ms-auto ps-auto ">
                <a href="{% url "review_create" %}">
                    <button type="button" class="btn btn-primary">+ Write A Review</button>
                </a>
            </div>
        </div>
    </div>
    {% if restaurant.reviews.all.count == 0 %}
        <p>There are no reviews yet</p>
    {% else %}
        {% for review in restaurant.reviews.all %}
        <div class="card my-1 py-2">
            <div class="card-body">
                <p>{{ review.user }} - &#9733; {{ review.rating}}-Star - Created {{ review.created }}</p>
                <p>{{ review.body }}</p>
                <a href="{% url "review_detail" review.pk %}"><button type="button" class="btn btn-secondary">Read Full Review</button></a>
            </div>
        </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock content %}

templates/review_create.html
<!--
Connor Warner
CIS 218
2/28/24
-->

{% extends "base.html" %}

{% block content %}
<div class="review mx-4">
    <header class="d-flex flex-wrap mt-3">
        <a href="{% url "home" %}" class="align-self-center">
            <button type="button" class="btn btn-secondary px-2 py-0 fs-4">&#8592;</button>
        </a>
        <div class="fs-1 ms-3 fw-bold">Write a Review</div>
    </header>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-success"type="submit" value="Save">
    </form>
</div>
{% endblock content %}

templates/review_delete.html
<!--
Connor Warner
CIS 218
2/28/24
-->

{% extends "base.html" %}

{% block content %}
<div class="mx-4">
    <header class="d-flex flex-wrap my-3">
        <a href="{% url "review_detail" review.pk %}" class="align-self-center">
            <button type="button" class="btn btn-secondary px-2 py-0 fs-4">&#8592;</button>
        </a>
        <div class="fs-1 fw-bold ms-3">{{ review.restaurant }} - Delete Review</div>
    </header>
    <div class="review my-1 py-2">
        <div class="card">
            <div class="card-body">
                <p>{{ review.user }} - &#9733; {{ review.rating}}-Star - Created {{ review.created }}</p>
                <p>{{ review.body }}</p>
            </div>
        </div>
    </div>
    <div>
        <p class="fw-bold fst-italic">Are you sure you want to delete this review?</p>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-danger" type="submit" value="&#x2613; Confirm">
        </form>
    </div>
</div>
{% endblock content %}

templates/review_detail.html
<!--
Connor Warner
CIS 218
2/28/24
-->

{% extends "base.html" %}

{% block content %}
<div class="review mx-4">
    <header class="d-flex flex-wrap mt-3">
        <a href="{% url "restaurant_detail" review.restaurant.pk %}" class="align-self-center">
            <button type="button" class="btn btn-secondary px-2 py-0 fs-4">&#8592;</button>
        </a>
        <div class="fs-1 fw-bold ms-3">{{ review.restaurant }} - Review Detail</div>
    </header>
    <div class="review my-1 py-2">
        <div class="card">
            <div class="card-body">
                <p>{{ review.user }} - &#9733; {{ review.rating}}-Star - Created {{ review.created }}</p>
                <p>{{ review.body }}</p>
                <a href="{% url "review_update" review.pk %}" class="text-decoration-none">
                    <button type="button" class="btn btn-success px-2 me-2">&#9998; Edit Review</button>
                </a>
                <a href="{% url "review_delete" review.pk %}" class="text-decoration-none">
                    <button type="button" class="btn btn-danger px-2">&#x2613; Delete Review</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/review_update.html
<!--
Connor Warner
CIS 218
2/28/24
-->

{% extends "base.html" %}

{% block content %}
<div class="review mx-4">
    <header class="d-flex flex-wrap mt-3">
        <a href="{% url "review_detail" review.pk %}" class="align-self-center">
            <button type="button" class="btn btn-secondary px-2 py-0 fs-4">&#8592;</button>
        </a>
        <div class="fs-1 fw-bold ms-3">{{ review.restaurant }} - Edit Review</div>
    </header>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-success">
    </form>
<div>
{% endblock content %}